# Generated by Django 4.2.6 on 2023-11-01 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catagory",
            options={"ordering": ("name",), "verbose_name_plural": "Catagoreis"},
        ),
    ]
