# Generated by Django 4.2.6 on 2023-11-30 00:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0004_alter_item_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="Catagory",
            new_name="catagory",
        ),
    ]
