# Generated by Django 4.2.6 on 2023-12-09 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0006_alter_catagory_options_rename_catagory_item_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="item.item",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="members",
            field=models.ManyToManyField(
                related_name="conversations", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="convesation_message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message",
                to="conversation.conversation",
            ),
        ),
    ]
