# Generated by Django 4.2.6 on 2023-12-09 13:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "conversation",
            "0002_alter_conversation_item_alter_conversation_members_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Convesation_message",
            new_name="ConvesationMessage",
        ),
    ]
