# Generated by Django 4.2.6 on 2023-12-09 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0003_rename_convesation_message_convesationmessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="convesationmessage",
            old_name="conversation",
            new_name="conversation",
        ),
    ]
